default:
  image: python:3.10
  tags: ['docker']

stages:
  - test

before_script:
  - echo 'before script'
  # - cp game.txt game-new.txt
  # - git cat-file -p origin/main:./game.txt > game-old.txt

test:
  stage: test
  script:
    - echo "TODO..."
