default:
  image: python:3.10
  tags: ['docker']

stages:
  - test
  - test-x
  - test-o

before_script:
  - echo 'before script'
  # - cp game.txt game-new.txt
  # - git cat-file -p origin/main:./game.txt > game-old.txt

test:
  stage: test
  script:
    - echo Start script
    - python3 tictactoe.py

test-x:
  stage: test
  script:
    - python3 test-x.py
  artifacts:
    expire_in: 1 day
    name: "game.txt"
    when: on_success
    untracked: true

test-o:
  stage: test
  script:
    - python3 test-o.py
  artifacts:
    expire_in: 1 day
    name: "game.txt"
    when: on_success
    untracked: true
